DROP TABLE IF EXISTS `wallet_summary`;


CREATE TABLE `wallet_summary` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`amount` DOUBLE NOT NULL,
`credited_date_time` DATETIME NOT NULL,
 current_balance DOUBLE NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';